version: "3"
services:

      
   market-front:
        image: szf2.satpay.ir/market-frontend
        container_name: market-frontend
        restart: unless-stopped

        build:
            context: .
            args:
                - ENV=$ENV
            dockerfile: Dockerfile
        ports:
            - 80:80

        environment:
            ASPNETCORE_ENVIRONMENT: $ENV
